name: "Sphinx: Render docs"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: actions/setup-python@v5
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Install Sphinx
      run: |
        pip install "sphinx>=6.0.0"

    - name: Install rtd
      run: |
        pip install sphinx-rtd-theme
    - name: Install numpydoc
      run: |
        pip install numpydoc
    # - name: Install dependencies 2
    #   run: |
    #     pip install sphinx sphinx_rtd_theme myst_parser
    - name: Build HTML
      # uses: ammaraskar/sphinx-action@master
      run: |
        sphinx-build docs _build
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/_build/html/
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/html/
        force_orphan: true
